---
title: "Group comparison"
format: html
---

# Question 1: Group Comparison

## Background

The data I'm working with is the art collection data set. This is from the TidyTuesday Github Repository. It contains information on artworks, artists, dates, physical dimensions, acquisition details and online metadata. The main question I'm answering is "does artwork width differ according to thumbnail copyright status?". We are seeing if there are significant changes with artwork width and thumbnail copyright status. One copyright status may favor wider artwork, whereas another may favor shorter art. My main hypothesis is that it may differ slightly as some thumbnail copyright status may prefer certain widths for policy and legal reasons. To see if my hypothesis is true, I will conduct a statistical analysis plan. I will plan out how I will do a statistical analysis on the data, deciding which variables to use, how to prepare it and what model to use to analyse it.

## Research aim

The aim of this research is to investigate whether artwork width will differ according to thumbnail copyright status. So, we will need to find patterns on width changing according to thumbnail copyright status. We can compare different widths for different thumbnail copyright status, and see if there is a pattern, or any significant difference between them. For example, the thumbnail copyright status "@Alex Katz" may have an average artwork width of 400, whereas "@Gerhard Richter" may be 200. There may be a small difference (50 - 100) however, comparing thumbnail copyright statuses will let us spot patterns to answer our question.

## Variables and data types

The variables that will be needed are width and thumbnail copyright. Width is numerical/continuous data, while thumbnail copyright is categorical data. This is all we need, as we are just focusing on width, rather than other aspects of the art like height or depth, and we are directly comparing thumbnail copyright status's with width.

## Data preparation

The data we have isn't fully filled in. So, we need to fix the data before we can analyse it. For some rows, data for width and thumbnail copyright are missing. So, we would need to transform these rows before we can analyse the data or conduct tests on it. We can transform it by making the missing data become the average of all widths. This way, we will get a more accurate answer, as missing data can affect means, standard deviation and more, so this is needed. More data preparation that may be needed is to remove outliers that are likely data entry errors. This can affect our analysis and produce the wrong conclusion, if there are enough data entry errors. Also, thumbnailCopyright may need to be transformed into simpler categories or limited to a few when doing the test. There are likely too many unique values, so reducing the nymber of categories may help with the analysis. There may also be unbalanced sample sizes. For example, we may have a large amount of data for one copyright status but a small amount for another. So filtering the data so we have equal/similar sample sizes will help with a more accurate analysis.

## Proposed method

The method I would use is a one-way ANOVA test. An ANOVA test will determine if there is a difference between means of two or more groups. A two-way ANOVA test won't work as it relies on two or more independent variables, whereas we are working with one (thumbnailCopyright) So, a one-way ANOVA will be most appropriate for the number of categories we are working with. Also, ANOVA is used to compare means between categories. Working out the mean for each copyright status will be useful to see any differences, so ANOVA is the most appropriate for our question. The reason why I wouldn't use a t-test for this, even though these tests are similar, is because a t-test only compares the means of 2 groups. Where as we have more than 2 groups in thumbnailCopyright, so we would need to conduct multiple t-tests. However, doing too many can produce a type I error. This makes the results unrelated. So, an ANOVA test will ensure we are testing all groups and get accurate results, rather than risking getting a type I error.

## Assumptions

Assumptions for ANOVA are normal distributions of residuals (difference between observed and predicted values), equal variance across observations and observations are independent from each other. These are assumptions that are made for all tests conducted with ANOVA. A normal distribution of residuals means that the distribution is symmetric around the mean. So, the residuals should produce a bell-shaped curve. This is also known as the Gaussian distribution. This is so our p-value is accurate, which will lead to the right conclusion of the test. Equal variance across groups means that two or more values have similar variance/spread. We assume this because unequal variance will lead to inaccurate p-values which will then lead to an incorrect conclusion. Observations being independent from each other means that the observations have no correlation with each other. 
## Diagnostics and model checks

We need to make sure that the assumptions we need for the ANOVA test are met. We do this through diagnostics and model checks. To test normality we can plot a histogram. It should create a bell shape with each bar. This means the center is the tallest one and each bar on the left and right gets smaller. It doesn't need to be a perfect bell shape but it should resemble one. To test equal variance we could do a side-by-side box plot. This way we can compare the variance across each cell visually. If the variance is similar, then this assumption is met and we can do the ANOVA test. To test variable independence, it's mostly done by observations of your data. For example, you can produce a residual plot to see if the data points are scattered randomly. If they have a non-random pattern, then it may suggest the variables aren't independent.

## Fallback strategy

If the diagnostic and model checks show problems, there are a few fallback models we can use instead. For example, if the variance is unequal, we can instead conduct a Welch ANOVA test, as it doesn't make the assumption of equal variance and is more robust. It adjusts it's calculations according to the variance so it doesn't need to assume equal variance. If the distribution is very distorted, then you can try and clean the data again in case there are any data entry errors and that all data types are consistent. You could also use a different statistical method like Bootstrap ANOVA. This version was designed to be a fallback model when the data isn't normally distributed. If independence in variables is found false, then we can use a mixed model solution instead. This model will account for data dependencies. It's best used for grouped data, which is what the data set we are working with is. Each thumbnail copyright status is a group with different artwork widths within those groups.

## Reporting and interpretation

When reporting the one-way ANOVA test, you will be reporting the f-statistic, degrees of freedom and the p-value. These will let you present the test's results. These are the values we are getting from doing the test, so reporting them will let others know your findings. Your p-value can be the most important as it tells you if the analysis was significant or not.

For interpretation, you will be interpreting whether thumbnail copyright status had an effect on your sample and if there are any patterns. If there is, you will know if your alternative hypothesis is correct.

## References

**AI WAS USED FOR THIS DOCUMENT: Used to make sure work makes sense and general research**

Crawley, M (2011) **Statistics: An Introduction Using R**. Wiley. Available at: https://ebookcentral.proquest.com/lib/harperadams/reader.action?docID=827080&c=UERG&ppg=1 (Accessed: 28/05/2026) 

Statistics How To (2021) Available at: https://www.statisticshowto.com/probability-and-statistics/hypothesis-testing/anova/ (Accessed: 12/05/2026)

MHango, J (2026) **The t-Test**. SQ4013: Thinking With Data. Available at: https://josephmhango.github.io/SQ4013/slides/ttest.html#/title-slide (Accessed: 16/05/2026)

MHango, J (2026) **Data and the scientific process** SQ4013: Thinking With Data. Available at: https://josephmhango.github.io/SQ4013/slides/null.html#/title-slide (Accessed: 16/05/2026)

DataCamp (2024) **ANOVA Test: An In-Depth Guide with Examples**. Available at: https://www.datacamp.com/tutorial/anova-test (Accessed: 20/05/2026)

IBM Skillsbuild (2023) **Data fundamentals**. Available at: https://skillsbuild.org/adult-learners/explore-learning/data-analyst (Accessed: 27/05/2026)
